name: Build with Webpack and Deploy to FTP

on:
  push:
    branches: [ "main" ]

jobs:
  build_deploy:
    name: ğŸ—ï¸ Build & Deploy
    runs-on: ubuntu-latest
    
    steps:
    - name: ğŸ“š Get latest code
      uses: actions/checkout@v3

    - name: ğŸ› ï¸ Build the website
      run: |
        npm install
        npm run build

    - name: ğŸ‰ Deploy website
      uses: SamKirkland/FTP-Deploy-Action@4.3.2
      with:
        server: ftp.cluster029.hosting.ovh.net
        username: ixzzylc
        password: ${{ secrets.password_ftp }}
        local-dir: build/
        server-dir: www/